import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import Sidebar from '@/components/sidebar';
import Header from '@/components/header';

const roboto = Roboto({
  subsets: ['cyrillic'],
});

export const metadata: Metadata = {
  title: 'Главная',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${roboto.className} antialiased`}>
        <Sidebar />
        <Header />
        <main className="mt-10 ml-0 p-5 lg:ml-60">
          <div className="mx-auto my-0 max-w-5xl px-6 py-4">{children}</div>
        </main>
      </body>
    </html>
  );
}
